using System;
using System.Collections.ObjectModel;
using System.IO;
using System.Windows;
using System.Windows.Threading;
using Microsoft.Data.Sqlite;

namespace FraudDashboard
{
    public partial class MainWindow : Window
    {
        // Observable collection for real-time UI data binding
        public ObservableCollection<FraudAlert> Alerts { get; set; }
        private DispatcherTimer _timer;
        private string _dbPath;

        public MainWindow()
        {
            InitializeComponent();
            Alerts = new ObservableCollection<FraudAlert>();
            AlertsList.ItemsSource = Alerts;

            // Resolve the absolute path to the SQLite database generated by the Python backend
            string currentDirectory = AppDomain.CurrentDomain.BaseDirectory;
            DirectoryInfo dir = new DirectoryInfo(currentDirectory).Parent.Parent.Parent.Parent;
            _dbPath = Path.Combine(dir.FullName, "bank_transactions.db");

            // Initialize the polling mechanism to fetch new threats every second
            _timer = new DispatcherTimer();
            _timer.Interval = TimeSpan.FromSeconds(1);
            _timer.Tick += LoadAlertsFromDatabase;
            _timer.Start();

            // Initial fetch
            LoadAlertsFromDatabase(null, null);
        }

        private void LoadAlertsFromDatabase(object sender, EventArgs e)
        {
            if (!File.Exists(_dbPath)) return;

            try
            {
                using (var connection = new SqliteConnection($"Data Source={_dbPath}"))
                {
                    connection.Open();
                    
                    // Fetch the 15 most recent alerts, ordered by ID descending
                    var command = connection.CreateCommand();
                    command.CommandText = "SELECT * FROM Live_Fraud_Alerts ORDER BY AlertID DESC LIMIT 15";

                    using (var reader = command.ExecuteReader())
                    {
                        Alerts.Clear(); 
                        while (reader.Read())
                        {
                            Alerts.Add(new FraudAlert
                            {
                                TransactionTime = reader["TransactionTime"].ToString(),
                                AccountText = $"Account: {reader["AccountID"]}",
                                AmountText = $"{reader["Amount"]} TRY",
                                Details = $"{reader["Device"]} -> {reader["Merchant"]}",
                                RiskText = $"Risk: {reader["RiskScore"]}%"
                            });
                        }
                    }

                    // Aggregate total blocked transactions for the status bar
                    var countCommand = connection.CreateCommand();
                    countCommand.CommandText = "SELECT COUNT(*) FROM Live_Fraud_Alerts";
                    var totalBlocked = (long)countCommand.ExecuteScalar();
                    TotalAlertsText.Text = $"Total Blocked: {totalBlocked}";
                }
            }
            catch (Exception)
            {
                // Silently handle I/O locks; the timer will retry in the next cycle
            }
        }
    }

    // Data model for WPF bindings
    public class FraudAlert
    {
        public string TransactionTime { get; set; }
        public string AccountText { get; set; }
        public string AmountText { get; set; }
        public string Details { get; set; }
        public string RiskText { get; set; }
    }
}